# Generated by Django 4.0.4 on 2022-05-06 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasktable_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.tasktable'),
        ),
    ]
